### ISSUE TITLE
Crash while downloading plots

### ISSUE THREAD

**Issue by pwestbro** [chiafactory/plotorder#11]
I am running plotorder in an Ubuntu VM, and I am seeing the following crash

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6a7e82]

goroutine 2297 [running]:
chiafactory/plotorder/plot.(*Plot).Download.func1()
        /home/runner/work/plotorder/plotorder/plot/plot.go:497 +0x42
chiafactory/plotorder/plot.(*Plot).Download(0xc0004798c0, {0x8bd098, 0xc00006e980})
        /home/runner/work/plotorder/plotorder/plot/plot.go:616 +0x926
chiafactory/plotorder/processor.(*Processor).process.func2()
        /home/runner/work/plotorder/plotorder/processor/processor.go:227 +0x6a
created by chiafactory/plotorder/processor.(*Processor).process
        /home/runner/work/plotorder/plotorder/processor/processor.go:225 +0x485

**Comment by pwestbro** [comment]
I have seen a similar crash on my Windows 11 machine:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x6d8982]

goroutine 2396 [running]:
chiafactory/plotorder/plot.(*Plot).Download.func1()
        /home/runner/work/plotorder/plotorder/plot/plot.go:497 +0x42
chiafactory/plotorder/plot.(*Plot).Download(0xc00036ef00, {0x8f6e18, 0xc00021c0c0})
        /home/runner/work/plotorder/plotorder/plot/plot.go:616 +0x930
chiafactory/plotorder/processor.(*Processor).process.func2()
        /home/runner/work/plotorder/plotorder/processor/processor.go:227 +0x6a
created by chiafactory/plotorder/processor.(*Processor).process
        /home/runner/work/plotorder/plotorder/processor/processor.go:225 +0x485
