### ISSUE TITLE
Crashes if the log file doesn't exist.

### ISSUE THREAD

**Issue by mumblingsages** [chiafactory/plotorder#2]
Following a fresh clone of the repo, the code assumes the log directory and file exists. Manually creating seems to work around the issue.

(venv) root@chia-digger:~/Development/plotorder# python3 main.py -help
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from client import ApiClient
  File "/root/Development/plotorder/client/__init__.py", line 9, in <module>
    from config.decorator import report_exception_issue
  File "/root/Development/plotorder/config/decorator.py", line 10, in <module>
    from .log import log
  File "/root/Development/plotorder/config/log.py", line 8, in <module>
    log.basicConfig(format='%(asctime)s [%(module)s:%(lineno)s - %(levelname)s]: %(message)s',
  File "/usr/lib/python3.8/logging/__init__.py", line 1976, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/lib/python3.8/logging/__init__.py", line 1143, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.8/logging/__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/root/Development/plotorder/log/chia.log'

**Comment by trepca** [comment]
Thanks for reporting, def a bug. We will be releasing an update later this week,

**Comment by trepca** [comment]
We have released a Go version where this issue is fixed, thanks.
