### ISSUE TITLE
400 error when downloading multiple plots

### ISSUE THREAD

**Issue by humaintenance** [chiafactory/plotorder#5]
The tool was working fine downloading just one plot, but once another was published I get the following output:

```
Exception occurred:
Error while getting response for order/plot ID=Y*****d: http_status=400, response={"id":["This field is required."]}
Will wait for 18 s and then retry.
```

It appears the download is still actually processing, as I can see the files growing, but the progress file doesn't get updated and the console just continually shows the above.

Here is the full trace from the log:

```
2021-06-23 19:24:38 GMT Summer Time [__init__:184 - INFO]: Reporting the plot ID=Y*****d download state via API.
2021-06-23 19:24:38 GMT Summer Time [__init__:265 - WARNING]: Non-200 status code while getting plots for order ID=Y*****d: 400.
2021-06-23 19:24:38 GMT Summer Time [__init__:267 - DEBUG]: {"id":["This field is required."]}
2021-06-23 19:24:38 GMT Summer Time [decorator:34 - ERROR]: Error while executing report_downloading
Traceback (most recent call last):
  File "C:\Users\USERNAME\Documents\GitHub\plotorder\config\decorator.py", line 24, in wrapper
    return method(*args, **kwargs)
  File "C:\Users\USERNAME\Documents\GitHub\plotorder\client\__init__.py", line 191, in report_downloading
    self._check_response(response, plot.plot_id)
  File "C:\Users\USERNAME\Documents\GitHub\plotorder\client\__init__.py", line 268, in _check_response
    raise ConnectionError(f'Error while getting response for order/plot ID={request_id}: '
ConnectionError: Error while getting response for order/plot ID=Y*****d: http_status=400, response={"id":["This field is required."]}
```

Here is my config file:
```
[API]
api_url=http://chiafactory.com/api/v1/
api_key=6***********************************6

[LOCAL]
plot_dir=X:\
progress_file=C:\Users\USERNAME\Documents\GitHub\plotorder\progress.log
```

EDIT:
As mentioned, the download does continue in the background despite the errors... however there is a retry limit which will then just stops the process entirely.

**Comment by trepca** [comment]
sorry for the late reply, this is, unfortunately, a very silly bug. You need to remove the trailing slash in api_url.

So instead of `api_url=http://chiafactory.com/api/v1/` it needs to be `api_url=https://chiafactory.com/api/v1` (I also added https)

We'll be publishing a new Go version soon.

**Comment by trepca** [comment]
New Go version is published.
